name: CI

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0

      - name: Install Clojure
        uses: DeLaGuardo/setup-clojure@master
        with:
          bb: latest
          clj-kondo: latest

      - name: Lint codebase
        run: bb lint

  unit-test:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        jdk: [8, 11, 15, 17]
        include:
          - os: windows-latest
            jdk: 8
          - os: macos-latest
            jdk: 8
    steps:
      - uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0

      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}

      - name: Install Clojure
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.10.3.1013'
          bb: latest

      - name: Run tests
        run: bb test

